// Calculate the total revenue generated by all sales transactions:
db.sales.aggregate([
  {
    $group: {
      _id: null,
      totalRevenue: { $sum: { $multiply: ["$quantity", "$price"] } },
    },
  },
]);

// Find the total quantity sold for each product:
db.sales.aggregate([
  {
    $group: {
      _id: "$product",
      totalQuantity: { $sum: "$quantity" },
    },
  },
]);

// Retrieve the top 5 products with the highest total revenue, along with their total revenue values:
db.sales.aggregate([
  {
    $group: {
      _id: "$product",
      totalRevenue: { $sum: { $multiply: ["$quantity", "$price"] } },
    },
  },
  {
    $sort: { totalRevenue: -1 },
  },
  {
    $limit: 5,
  },
]);
